function stop = convergence_criterion_en(num_iters,max_iters,...
                t,alpha,w,diff,tol)
    stop = ((num_iters >= 40) && (norm((1-alpha)*t*w + diff,inf) <= ...
            alpha*t*(1 + tol))) || (num_iters >= max_iters);
end