function stop = convergence_criterion_inf(num_iters,max_iters,...
                t,diff,tol)
    stop = ((num_iters >= 40) && (norm(diff,1) <= ...
            t*(1 + tol))) || (num_iters >= max_iters);
end